#!/bin/bash
set -e

while test $# -gt 0;do
  OPT=$1
  shift

  case $OPT in
    -f | --forecolor)
      case ${1,,} in
        black)                       FC="\033[0;30m"; shift;;
        red)                         FC="\033[0;31m"; shift;;
        green)                       FC="\033[0;32m"; shift;;
        orange)                      FC="\033[0;33m"; shift;;
        blue)                        FC="\033[0;34m"; shift;;
        purple)                      FC="\033[0;35m"; shift;;
        cyan)                        FC="\033[0;36m"; shift;;
        lgray    | lightgray)        FC="\033[0;37m"; shift;;
        dgray    | darkgray)         FC="\033[1;30m"; shift;;
        lred     | lightred)         FC="\033[1;31m"; shift;;
        lgreen   | lightgreen)       FC="\033[1;32m"; shift;;
        yellow)                      FC="\033[1;33m"; shift;;
        lblue    | lightblue)        FC="\033[1;34m"; shift;;
        lpurple  | lightpurple)      FC="\033[1;35m"; shift;;
        lcyan    | lightcyan)        FC="\033[1;36m"; shift;;
        white)                       FC="\033[1;37m"; shift;;
        nc | nocolor | none)         FC="\033[0m"   ; shift;;
      esac
    ;;
    -b | --backcolor)
      case ${1,,} in
        black)                       BC="\033[0;40m"; shift;;
        red)                         BC="\033[0;41m"; shift;;
        green)                       BC="\033[0;42m"; shift;;
        orange)                      BC="\033[0;43m"; shift;;
        blue)                        BC="\033[0;44m"; shift;;
        purple)                      BC="\033[0;45m"; shift;;
        cyan)                        BC="\033[0;46m"; shift;;
        lgray    | lightgray)        BC="\033[0;47m"; shift;;
        dgray    | darkgray)         BC="\033[1;40m"; shift;;
        lred     | lightred)         BC="\033[1;41m"; shift;;
        lgreen   | lightgreen)       BC="\033[1;42m"; shift;;
        yellow)                      BC="\033[1;43m"; shift;;
        lblue    | lightblue)        BC="\033[1;44m"; shift;;
        lpurple  | lightpurple)      BC="\033[1;45m"; shift;;
        lcyan    | lightcyan)        BC="\033[1;46m"; shift;;
        white)                       BC="\033[1;47m"; shift;;
        nc | nocolor | none)         BC="\033[0m"   ; shift;;
      esac
    ;;
    *)  if test $# -gt 0;then ECHO="$ECHO${FC}${BC}$OPT ";else ECHO="$ECHO${FC}${BC}$OPT";fi;;
  esac
done
echo -e "$ECHO\033[0m"
