#!/bin/bash
set -e

usage () {
  echo
  echo "Aufruf: wh --forecolor <color> --backcolor <color> \"Text\""
  echo
  echo "Gibt Text (mehr)farbig auf der Konsole aus. "
  echo
  echo -e "\e[4mOption:\e[0m"
  echo
  echo "  -f   --forecolor   Vordergrundfarbe setzen (kann mehrfach angegebn werden). "
  echo "  -b   --backcolor   Hintergrundfarbe setzen (kann mehrfach angegebn werden). "
  echo "  -h   --help        Ruft diese Hilfe auf. "
  echo
  echo -e "\e[4mBeispiel:\e[0m"
  echo
  echo "  wh -f green \"Dies ist\" -f red \"ein Beispiel\n\" -b white -f blue \"mit Zeilenumbruch\""
  echo
  echo -e "\e[4mErgebnis:\e[0m"
  echo
  echo -e "  \e[0;32mDies ist \e[0;31mein Beispiel\n  \e[0;34m\e[1;47mmit Zeilenumbruch\e[0m"
  echo
}

FC=0
BC=0
while test $# -gt 0;do
  OPT=$1
  shift

  case $OPT in
    -f | --forecolor)
      case ${1,,} in
        black)                       FC="30"; shift;;
        red)                         FC="31"; shift;;
        green)                       FC="32"; shift;;
        orange)                      FC="33"; shift;;
        blue)                        FC="34"; shift;;
        purple)                      FC="35"; shift;;
        cyan)                        FC="36"; shift;;
        lgray    | lightgray)        FC="37"; shift;;
        dgray    | darkgray)         FC="90"; shift;;
        lred     | lightred)         FC="91"; shift;;
        lgreen   | lightgreen)       FC="92"; shift;;
        yellow)                      FC="93"; shift;;
        lblue    | lightblue)        FC="94"; shift;;
        lpurple  | lightpurple)      FC="95"; shift;;
        lcyan    | lightcyan)        FC="96"; shift;;
        white)                       FC="97"; shift;;
        nc | nocolor | none)         FC="0" ; shift;;
        *)                                    shift;;
      esac
    ;;
    -b | --backcolor)
      case ${1,,} in
        black)                       BC="40";  shift;;
        red)                         BC="41";  shift;;
        green)                       BC="42";  shift;;
        orange)                      BC="43";  shift;;
        blue)                        BC="44";  shift;;
        purple)                      BC="45";  shift;;
        cyan)                        BC="46";  shift;;
        lgray    | lightgray)        BC="47";  shift;;
        dgray    | darkgray)         BC="100"; shift;;
        lred     | lightred)         BC="101"; shift;;
        lgreen   | lightgreen)       BC="102"; shift;;
        yellow)                      BC="103"; shift;;
        lblue    | lightblue)        BC="104"; shift;;
        lpurple  | lightpurple)      BC="105"; shift;;
        lcyan    | lightcyan)        BC="106"; shift;;
        white)                       BC="107"; shift;;
        nc | nocolor | none)         BC="0"  ; shift;;
        *)                                    shift;;
      esac
    ;;
    -h | --help)
       usage
       exit 0
    ;;
    *)  if [[ $# -gt 0 && ! "$OPT" =~ .*\n$ ]];then ECHO="$ECHO\e[${FC};${BC}m$OPT ";else ECHO="$ECHO\e[${FC};${BC}m$OPT";fi;;
  esac
done
echo -e "$ECHO\e[0m"
